set_property SRC_FILE_INFO {cfile:/home/francesco/Documents/mmr-kria-hardware-design/mmr-kria-hardware-design.srcs/constrs_1/new/fan.xdc rfile:../../../mmr-kria-hardware-design.srcs/constrs_1/new/fan.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/francesco/Documents/mmr-kria-hardware-design/mmr-kria-hardware-design.srcs/constrs_1/new/gpio.xdc rfile:../../../mmr-kria-hardware-design.srcs/constrs_1/new/gpio.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A12 [get_ports {fan}]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F8 [get_ports {led_uf1_tri_io[0]}]
