# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/fan.xdc

# XDC: new/gpio.xdc

# XDC: new/can.xdc

# XDC: new/uart.xdc

# XDC: new/spi.xdc

# Block Designs: bd/pl_design/pl_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pl_design || ORIG_REF_NAME==pl_design} -quiet] -quiet

# IP: bd/pl_design/ip/pl_design_zynq_ultra_ps_e_0_0/pl_design_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pl_design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==pl_design_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/pl_design/ip/pl_design_xlslice_0_0/pl_design_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pl_design_xlslice_0_0 || ORIG_REF_NAME==pl_design_xlslice_0_0} -quiet] -quiet

# IP: bd/pl_design/ip/pl_design_xbar_0/pl_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pl_design_xbar_0 || ORIG_REF_NAME==pl_design_xbar_0} -quiet] -quiet

# IP: bd/pl_design/ip/pl_design_axi_interconnect_0_0/pl_design_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pl_design_axi_interconnect_0_0 || ORIG_REF_NAME==pl_design_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/pl_design/ip/pl_design_axi_gpio_0_1/pl_design_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pl_design_axi_gpio_0_1 || ORIG_REF_NAME==pl_design_axi_gpio_0_1} -quiet] -quiet

# IP: bd/pl_design/ip/pl_design_proc_sys_reset_0_0/pl_design_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pl_design_proc_sys_reset_0_0 || ORIG_REF_NAME==pl_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/pl_design/ip/pl_design_axi_gpio_0_2/pl_design_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pl_design_axi_gpio_0_2 || ORIG_REF_NAME==pl_design_axi_gpio_0_2} -quiet] -quiet

# IP: bd/pl_design/ip/pl_design_auto_pc_0/pl_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pl_design_auto_pc_0 || ORIG_REF_NAME==pl_design_auto_pc_0} -quiet] -quiet

# XDC: /home/cristian/Desktop/formula/mmr-kria-hardware-design/mmr-kria-hardware-design.gen/sources_1/bd/pl_design/pl_design_ooc.xdc
